# You should adapt it to your project's needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml).
# After you've adjusted this file to your liking, commit it to your remote git repository to share the Gitpod configuration with others.

# If you need to start from a template, Gitpod provides ready-to-use ones: https://www.gitpod.io/docs/introduction/getting-started/quickstart

image:
  file: .gitpod.Dockerfile

tasks:
  # The 'init' command is run once at the start of workspace creation.
  # It is typically used for installing project dependencies, as in this case.
  - init: |
      pip install -r requirements.txt
      # Add any other necessary commands here
